// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package todoapp

import (
	"database/sql"
)

type Task struct {
	ID          int64
	Name        string
	Description sql.NullString
	Done        bool
}
